# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_make_room_widget(object):
    def setupUi(self, make_room_widget):
        make_room_widget.setObjectName("make_room_widget")
        make_room_widget.resize(400, 300)
        make_room_widget.setMinimumSize(QtCore.QSize(400, 300))
        make_room_widget.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(make_room_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(make_room_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.makeroom_name_lineEdit = QtWidgets.QLineEdit(make_room_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.makeroom_name_lineEdit.setFont(font)
        self.makeroom_name_lineEdit.setObjectName("makeroom_name_lineEdit")
        self.horizontalLayout.addWidget(self.makeroom_name_lineEdit, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(make_room_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.makeroom_password_lineEdit = QtWidgets.QLineEdit(make_room_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.makeroom_password_lineEdit.setFont(font)
        self.makeroom_password_lineEdit.setObjectName("makeroom_password_lineEdit")
        self.horizontalLayout_3.addWidget(self.makeroom_password_lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.makeroom_pushButton = QtWidgets.QPushButton(make_room_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.makeroom_pushButton.setFont(font)
        self.makeroom_pushButton.setDefault(False)
        self.makeroom_pushButton.setFlat(False)
        self.makeroom_pushButton.setObjectName("makeroom_pushButton")
        self.verticalLayout_2.addWidget(self.makeroom_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(make_room_widget)
        self.makeroom_pushButton.clicked.connect(make_room_widget.showRoomWindow) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(make_room_widget)

    def retranslateUi(self, make_room_widget):
        _translate = QtCore.QCoreApplication.translate
        make_room_widget.setWindowTitle(_translate("make_room_widget", "방 만들기"))
        self.label.setText(_translate("make_room_widget", "방 이름"))
        self.label_2.setText(_translate("make_room_widget", "비밀번호"))
        self.makeroom_pushButton.setText(_translate("make_room_widget", "방 만들기"))
