# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(540, 360)
        login_window.setMinimumSize(QtCore.QSize(540, 360))
        login_window.setMaximumSize(QtCore.QSize(540, 360))
        login_window.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.login_nickname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_nickname_lineEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_nickname_lineEdit.setFont(font)
        self.login_nickname_lineEdit.setInputMask("")
        self.login_nickname_lineEdit.setText("")
        self.login_nickname_lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.login_nickname_lineEdit.setClearButtonEnabled(False)
        self.login_nickname_lineEdit.setObjectName("login_nickname_lineEdit")
        self.horizontalLayout.addWidget(self.login_nickname_lineEdit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.login_enter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_enter_pushButton.setFont(font)
        self.login_enter_pushButton.setObjectName("login_enter_pushButton")
        self.horizontalLayout.addWidget(self.login_enter_pushButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        self.login_enter_pushButton.clicked.connect(login_window.showMainWindow) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Chatty Chatty"))
        self.label.setText(_translate("login_window", "Chatty Chatty"))
        self.label_3.setText(_translate("login_window", "made by team.아바라"))
        self.label_2.setText(_translate("login_window", "닉네임"))
        self.login_nickname_lineEdit.setPlaceholderText(_translate("login_window", "닉네임을 입력하세요"))
        self.login_enter_pushButton.setText(_translate("login_window", "입장"))
