# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/make_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_make_room_Dialog(object):
    def setupUi(self, make_room_Dialog):
        make_room_Dialog.setObjectName("make_room_Dialog")
        make_room_Dialog.resize(400, 200)
        make_room_Dialog.setMinimumSize(QtCore.QSize(400, 200))
        make_room_Dialog.setMaximumSize(QtCore.QSize(400, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(make_room_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(31, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(make_room_Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.room_title_lineEdit = QtWidgets.QLineEdit(make_room_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.room_title_lineEdit.sizePolicy().hasHeightForWidth())
        self.room_title_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.room_title_lineEdit.setFont(font)
        self.room_title_lineEdit.setObjectName("room_title_lineEdit")
        self.horizontalLayout.addWidget(self.room_title_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(make_room_Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.password_lineEdit = QtWidgets.QLineEdit(make_room_Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout_2.addWidget(self.password_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.make_pushButton = QtWidgets.QPushButton(make_room_Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.make_pushButton.setFont(font)
        self.make_pushButton.setObjectName("make_pushButton")
        self.horizontalLayout_3.addWidget(self.make_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(make_room_Dialog)
        self.make_pushButton.clicked.connect(make_room_Dialog.showRoomWindow) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(make_room_Dialog)

    def retranslateUi(self, make_room_Dialog):
        _translate = QtCore.QCoreApplication.translate
        make_room_Dialog.setWindowTitle(_translate("make_room_Dialog", "방 만들기"))
        self.label.setText(_translate("make_room_Dialog", "방 이름"))
        self.label_2.setText(_translate("make_room_Dialog", "비밀번호"))
        self.make_pushButton.setText(_translate("make_room_Dialog", "방 만들기"))
