# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_dialog(object):
    def setupUi(self, server_dialog):
        server_dialog.setObjectName("server_dialog")
        server_dialog.resize(650, 300)
        server_dialog.setMinimumSize(QtCore.QSize(650, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(server_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(server_dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.server_label = QtWidgets.QLabel(server_dialog)
        self.server_label.setObjectName("server_label")
        self.verticalLayout_2.addWidget(self.server_label)
        self.server_textEdit = QtWidgets.QTextEdit(server_dialog)
        self.server_textEdit.setAutoFillBackground(False)
        self.server_textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.server_textEdit.setTabChangesFocus(True)
        self.server_textEdit.setDocumentTitle("")
        self.server_textEdit.setUndoRedoEnabled(False)
        self.server_textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.server_textEdit.setLineWrapColumnOrWidth(80)
        self.server_textEdit.setReadOnly(True)
        self.server_textEdit.setOverwriteMode(False)
        self.server_textEdit.setTabStopWidth(80)
        self.server_textEdit.setAcceptRichText(True)
        self.server_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.server_textEdit.setObjectName("server_textEdit")
        self.verticalLayout_2.addWidget(self.server_textEdit)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(server_dialog)
        QtCore.QMetaObject.connectSlotsByName(server_dialog)

    def retranslateUi(self, server_dialog):
        _translate = QtCore.QCoreApplication.translate
        server_dialog.setWindowTitle(_translate("server_dialog", "Dialog"))
        self.label.setText(_translate("server_dialog", "Chatty Chatty 서버"))
        self.server_label.setText(_translate("server_dialog", "서버 실행중..."))
        self.server_textEdit.setHtml(_translate("server_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
